version: '3'

volumes:
  store:
    driver: local
  bundle:
    driver: local

services:
  nginx:
    build: ./nginx
    ports:
      - 80:8080
    volumes:
      - ./frontend/dist:/wwwroot:ro
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/dist:/app/dist
    links:
      - web
  web:
    build: .
    ports:
      - 3001:3001
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    links:
      - db
    stdin_open: true
    tty: true
    command: ./scripts/backend.sh
    environment: &app_env
      PORT: 3001
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: rails_docker_database
      DB_USER: postgres
      DB_PSWD: postgres
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rails_docker_database
